# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm7550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter benz,$(TARGET_DEVICE)),)

endif
